language: ruby
cache: bundler
rvm:
- 2.4.0
script: bundle exec rspec spec
notifications:
  slack:
    secure: e+2Ct7kYusI/0p4LnCd7M0mmt7Pq+EkYnDO9dSfNAUzTjI0ElOAnHygKVNw6QIOw52bu+iH2g3LvrMxTPSHaTGoonuXjps8cbsfBI3P7crmojmsRQJg6H+yMlibg1ls0nIC0w2y1GVxKXnE0TwgFTHdO2JYDl4toOKI8n066dWHutOK0JGNyBCxFc1xtP44OAYoXSbKYPZMUApEM4OUzM6047v73ukh5Fs4wjMhifkQj/SeBnQiECQgSmEnjoFShy13Tb2grzvyfApl3MMbK6ujqtzCrYsVGzjwmEv/rPw90eZfbO9UhJ9byDPr6t6Rf9bxLjKw3xJCLQpeQonFfYuFbj3H3+/KzcKrHg7wtMk33ywS8SQvBTpO1ASpGY6L8uhfsMsNGtBjKbGBQCZFmgawDqyl7ENBlLwErb/JeqhEkCWSbtVL5kglxeBGp9+2h4lRhafLm0NEj4fAmb/SDgiLUFQxLjcsGGpwS/yR4EJ6lcituUX4jytQEQmJFB7/LYQbI3nlkG4DcSfozQHxMG4Z6Uk1rvqO8nmiRLzreQybznQY0szMSo0ZK5IulbADWxbTd79i9cURXAFOR1GoT+FIEmxFf0HZ0wfRCkfsRa/NxnOld/4nhSjAVR/R/XHuTsyCOgwJCkAin6r6hc3a6zb7RrRiBENhxhF21FLnVOic=
