language: ruby
cache: bundler
rvm:
  - 2.4.0
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token:
      secure: CetXHMnyQ/3zQjKN7319MpokkarOukKNjwckkr6hOE/SEMGikDrRt6YTppMtkeZeDiAc7cDpZ78mofJC5CoNXGY9JlU/8MWE4TJlxtLRddYz0ObHwH7p7fMLSU3B5ZZl585AkDYyHse1/PDlmm1HuLlPuZ2McQIqY2tUWeUaInTpVl/HiTmqO8bmuZrN5V+HYx4NMnqS2uKmi5LFxN6hoSmFC1J7yJfoQ+uFC2e0ndNtmSsApVadsUxHEY4dhS3CcHXrgCol5CT4DmHKbpUIZbM8u4atxBPEz7/PqcsF+VwpjPpeCzhCj4WRO9GALwXhNTOUaRMrqPQ8rM6r+lhHXgOwhLdDPvqjOECQaAfOWeV6jC+WpjICgPQrPVGxbOSev3qEOQGrrkNTkg1Rn4kT8/WKoLdABGG1TVnoLMlCnvVQSI0R70iimQ7BuGKtCfrk7VDFyHrVVhHcYiHFodzpdFu05lEN07lmpqMQ4B+KQjgArHZ8cBPuwJosJm9VO5TEt6SiNvUauvgAoSiwc4cESs0hbyEMwyiatup5AE/gEnUamhxWiqyF235mLrN10+XVXjEI5AkiRx2t5vGertBUZtW21mvO5jSSNOIOvGeLFKfIuiAXGRmlFeUkvsxAaaWUNX/dLWxrYgPMognJg7uOGpNPp1ZVUctgVdneZphztLI=
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  slack:
    secure: e+2Ct7kYusI/0p4LnCd7M0mmt7Pq+EkYnDO9dSfNAUzTjI0ElOAnHygKVNw6QIOw52bu+iH2g3LvrMxTPSHaTGoonuXjps8cbsfBI3P7crmojmsRQJg6H+yMlibg1ls0nIC0w2y1GVxKXnE0TwgFTHdO2JYDl4toOKI8n066dWHutOK0JGNyBCxFc1xtP44OAYoXSbKYPZMUApEM4OUzM6047v73ukh5Fs4wjMhifkQj/SeBnQiECQgSmEnjoFShy13Tb2grzvyfApl3MMbK6ujqtzCrYsVGzjwmEv/rPw90eZfbO9UhJ9byDPr6t6Rf9bxLjKw3xJCLQpeQonFfYuFbj3H3+/KzcKrHg7wtMk33ywS8SQvBTpO1ASpGY6L8uhfsMsNGtBjKbGBQCZFmgawDqyl7ENBlLwErb/JeqhEkCWSbtVL5kglxeBGp9+2h4lRhafLm0NEj4fAmb/SDgiLUFQxLjcsGGpwS/yR4EJ6lcituUX4jytQEQmJFB7/LYQbI3nlkG4DcSfozQHxMG4Z6Uk1rvqO8nmiRLzreQybznQY0szMSo0ZK5IulbADWxbTd79i9cURXAFOR1GoT+FIEmxFf0HZ0wfRCkfsRa/NxnOld/4nhSjAVR/R/XHuTsyCOgwJCkAin6r6hc3a6zb7RrRiBENhxhF21FLnVOic=
